FROM phpdockerio/php:8.1-fpm
# https://github.com/bitrixdock/bitrixdock/blob/master/php81/Dockerfile

LABEL org.opencontainers.image.authors="Dmitry Verkhoturov <paskal.07@gmail.com>" \
      org.opencontainers.image.description="PHP 8.1 with everything needed for Bitrix" \
      org.opencontainers.image.documentation="https://github.com/paskal/bitrix.infra" \
      org.opencontainers.image.source="https://github.com/paskal/bitrix.infra.git" \
      org.opencontainers.image.title="php"

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
    php8.1-memcached \
    php8.1-memcache \
    php8.1-mbstring \
    php8.1-mysql \
    php8.1-intl \
    php8.1-interbase \
    php8.1-redis \
    php8.1-soap \
    php8.1-gd \
    php8.1-imagick \
    php8.1-opcache \
    php8.1-zip \
    php8.1-xdebug \
    php-pear php8.1-dev libmcrypt-dev gcc make autoconf libc-dev pkg-config \
    webp \
    msmtp \
    msmtp-mta \
    sudo \
    cron \
    && pecl install mcrypt-1.0.6 \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# msmtp to allow email sending
# msmtp-mta to allow sendmail usage with msmtp
# sudo to allow create logfile with www-data user
# cron to run cronjobs in a separate container

# without this, php container won't work if you forget to mount 90-php.ini
COPY ./90-php.ini /etc/php/8.1/fpm/conf.d/90-php.ini
COPY ./90-php.ini /etc/php/8.1/cli/conf.d/90-php.ini
# disable xdebug by default as it affects performance badly
COPY ./xdebug.ini /etc/php/8.1/mods-available/xdebug.ini

RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data

EXPOSE 9000
