FROM phpdockerio/php:8.3-fpm
# https://github.com/bitrixdock/bitrixdock/blob/master/php/php83/Dockerfile

LABEL org.opencontainers.image.authors="Dmitry Verkhoturov <paskal.07@gmail.com>" \
      org.opencontainers.image.description="PHP-fpm 8.3 with everything needed for Bitrix" \
      org.opencontainers.image.documentation="https://github.com/paskal/bitrix.infra" \
      org.opencontainers.image.source="https://github.com/paskal/bitrix.infra.git" \
      org.opencontainers.image.title="php"

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
    php8.3-gd \
    php8.3-imagick \
    php8.3-interbase \
    php8.3-intl \
    php8.3-mbstring \
    php8.3-mcrypt \
    php8.3-memcache \
    php8.3-memcached \
    php8.3-mysql \
    php8.3-opcache \
    php8.3-redis \
    php8.3-soap \
    php8.3-xdebug \
    php8.3-zip \
    webp \
    msmtp \
    msmtp-mta \
    sudo \
    cron \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# msmtp to allow email sending
# msmtp-mta to allow sendmail usage with msmtp
# sudo to allow create logfile with www-data user
# cron to run cronjobs in a separate container

# without this, php in the container won't work if you forget to mount 90-php.ini
COPY ./90-php.ini /etc/php/8.3/fpm/conf.d/90-php.ini
COPY ./90-php.ini /etc/php/8.3/cli/conf.d/90-php.ini
# disable xdebug by default as it affects performance badly
COPY ./xdebug.ini /etc/php/8.3/mods-available/xdebug.ini

RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data

# Security: prevent www-data from using cron and harden file permissions
RUN echo "www-data" >> /etc/cron.deny && \
    chmod 644 /etc/cron.deny && \
    chmod -R 755 /etc/php/ && \
    chown -R root:root /etc/php/

HEALTHCHECK --interval=30s --timeout=10s --retries=10 --start-period=10s \
  CMD php --ini || exit 1

EXPOSE 9000
