FROM unit:php8.2
# https://github.com/tippexs/nginxspace/blob/master/dev/Dockerfile

LABEL org.opencontainers.image.authors="Dmitry Verkhoturov <paskal.07@gmail.com>" \
      org.opencontainers.image.description="Nginx Unit with PHP 8.2 with everything needed for Bitrix" \
      org.opencontainers.image.documentation="https://github.com/paskal/bitrix.infra" \
      org.opencontainers.image.source="https://github.com/paskal/bitrix.infra.git" \
      org.opencontainers.image.title="php"

#RUN apt-get update \
#    && -y apt-transport-https lsb-release ca-certificates wget \
#    && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
#    && sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list' \
#    && apt-get update \
#    && apt-get -y --no-install-recommends install \
#    php8.2-gd \
#    php8.2-imagick \
#    php8.2-interbase \
#    php8.2-intl \
#    php8.2-mbstring \
#    php8.2-mcrypt \
#    php8.2-memcache \
#    php8.2-memcached \
#    php8.2-mysql \
#    php8.2-opcache \
#    php8.2-redis \
#    php8.2-soap \
#    php8.2-xdebug \
#    php8.2-zip \
#    webp \
#    msmtp \
#    msmtp-mta \
#    sudo \
#    cron \
#    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# msmtp to allow email sending
# msmtp-mta to allow sendmail usage with msmtp
# sudo to allow create logfile with www-data user
# cron to run cronjobs in a separate container

# without this, php in the container won't work properly
COPY ./90-php.ini /etc/php/php.ini

RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data

COPY nginx-unit.json /docker-entrypoint.d/.unit.conf.json

EXPOSE 8090 8091 8092 8093

CMD ["unitd", "--no-daemon", "--control", "unix:/var/run/control.unit.sock"]
