name: pull

on:
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  build-images:
    name: Pull code from master to favor-group.ru
    if: github.repository == 'paskal/bitrix.infra' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: pull newest code to favor-group.ru from master
        env:
          UPDATER_KEY: ${{ secrets.UPDATER_KEY }}
        run: curl -fsS --retry 3 --retry-all-errors --retry-delay 2 "https://hooks.favor-group.ru/update/pull-code/${UPDATER_KEY}"
